alpha/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import alpha.views
import assets
import ops


def i18n_javascript(request):
    return admin.site.i18n_javascript(request)

urlpatterns = [
    url(r'^admin/jsi18n', i18n_javascript),
    url(r'^admin/', admin.site.urls),
    url(r'^$', alpha.views.index, name='index'),
    url(r'^assets/', include('assets.urls')),
    url(r'^ops/', include('ops.urls')),
    url(r'^app/', include('applications.urls')),
    url(r'^services/', include('services.urls')),
]

assets/urls.py
from django.conf.urls import url


import assets.views

urlpatterns = [
    url(r'servers/', assets.views.servers_list, name='servers'),
    url(r'server_detail/([0-9a-zA-Z\-]{36})/$', assets.views.server_detail, name='server_detail'),
    url(r'add/', assets.views.server_add, name='server_add'),
    url(r'del/', assets.views.server_del, name='server_del'),
    url(r'update/([0-9a-zA-Z\-]{36})/$', assets.views.server_update, name='server_update'),
]

ops/urls.py
from django.conf.urls import url
from django.contrib import admin

import ops.views

urlpatterns = [
    url(r'^/', ops.views.index),
    # url(r'^ssh/([0-9a-zA-Z\-]{36})', ops.views.webssh, name='webssh'),
    # url(r'^ssh/', ops.views.webssh, name='webssh'),
    # url(r'websocket/([0-9a-zA-Z\-]{36})', ops.views.websocket, name='websocket'),
]

assets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import django.utils.timezone as timezone

# Create your models here.
import uuid


product_item = (
    (0, '电商1.0'),
    (1, '电商2.0'),
    (2, '电商3.0'),
    (3, 'NEC'),
    (4, '运维支撑'),
    (5, '大数据')
)


class Servers(models.Model):

    server_status = (
        (0, 'ON'),
        (1, 'OFF'),
    )

    system_info = (
        (0, 'CentOS6.0'),
        (1, 'CentOS6.5'),
        (2, 'CentOS7.0'),
        (4, 'CentOS7.2'),
        (5, 'Windows2008'),
        (6, 'Windows2012'),
    )

    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    HostName = models.CharField(max_length=20, blank=True, null=True, verbose_name='主机名')
    EIP = models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')
    IIP = models.GenericIPAddressField(verbose_name='内网IP')
    Status = models.SmallIntegerField(choices=server_status, default=0, verbose_name='状态')
    SystemInfo = models.SmallIntegerField(choices=system_info, default=0, verbose_name='系统信息')
    Mem = models.IntegerField(default=8, verbose_name='内存')
    CPU = models.IntegerField(default=4)
    SysDisk = models.IntegerField(default=50, verbose_name='系统盘')
    DataDisk = models.IntegerField(default=500, verbose_name='数据盘')
    Applications = models.ManyToManyField('Applications', verbose_name='应用')
    ProductItem = models.SmallIntegerField(choices=product_item, default=6, verbose_name='产品线')
    ExpirationDate = models.DateField(default=timezone.now, verbose_name='到期时间')
    # verbose_name,别名,在admin后台展示时用到

    # python2.x
    def __unicode__(self):
        return self.IIP

    # python3.x
    def __str__(self):
        return self.IIP

    class Meta:
        verbose_name_plural = '服务器'
        # admin中显示的名称


class Applications(models.Model):

    application_status = (
        (0, 'ON'),
        (1, 'OFF'),
    )

    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    Name = models.CharField(max_length=20, verbose_name='应用名')
    Version = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='版本号')
    InstallDir = models.CharField(max_length=256, verbose_name='安装目录')
    Port = models.IntegerField(verbose_name='端口')
    Status = models.IntegerField(choices=application_status, default=1, verbose_name='状态')
    ProductItem = models.SmallIntegerField(choices=product_item, default=6, verbose_name='产品线')

    # python2.x
    def __unicode__(self):
        return self.Name

    # python3.x
    def __str__(self):
        return self.Name

    class Meta:
        verbose_name_plural = '应用'


class User(models.Model):

    role = (
        (0, 'user'),
        (1, 'admin')
    )

    Name = models.CharField(max_length=20, verbose_name='名字')
    Email = models.EmailField(verbose_name='邮箱')
    Head_img = models.ImageField(verbose_name='用户头像', height_field=160, width_field=160,
                                 default='static/alpha/uploads/UserHeadImg/default.jpg',
                                 upload_to='static/alpha/uploads/UserHeadImg')
    Role = models.SmallIntegerField(choices=role, default=0)

alpha/forms.py
#! _*_ coding:utf8 _*_

from django import forms
from django.forms import ModelForm
import assets.models


class ServersModuleForm(ModelForm):
    class Meta:
        # 使用模型Servers中的所有字段
        model = assets.models.Servers
        fields = '__all__'

    # 自定义ExpirationDate样式,覆盖掉之前的,新加自定义日历样式
    ExpirationDate = forms.DateField(
        widget=forms.DateTimeInput(
            attrs={'type': 'date',
                   }
        ),
        label='到期时间'
    )


class ApplicationsModuleForm(ModelForm):
    class Meta:
        model = assets.models.Applications
        fields = '__all__'

        widgets = {
            'Name': forms.Select(
                choices=(
                    ('Nginx', 'Nginx'),
                    ('Tomcat', 'Tomcat'),
                    ('MySQL', 'MySQL'),
                    ('Redis', 'Redis'),
                    ('Sentinel', 'Sentinel'),
                    ('Logstash', 'Logstash'),
                    ('Kibana', 'Kibana'),
                    ('PHP', 'PHP'),
                    ('MongoDB', 'MongoDB'),
                    ('Dubbo', 'Dubbo'),
                    ('Zabbix', 'Zabbix'),
                    ('Jenkins', 'Jenkins'),
                    ('Confluence', 'Confluence'),
                    ('Gitlab', 'Gitlab'),
                    ('FastDFS', 'FastDFS'),
                    ('Zentao', 'Zentao'),
                    ('Nexus', 'Nexus'),
                    ('Keepalived', 'Keepalived'),
                    ('Haproxy', 'Haproxy'),
                )
            )
        }

alpha/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'index.html')

assets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
from assets.models import Servers
import alpha.forms
import json


# 服务器列表
def servers_list(request, number=10):
    servers = Servers.objects.all().order_by('id')
    paginator = Paginator(servers, number)
    page = request.GET.get('page')
    try:
        servers_obj = paginator.page(page)
    except PageNotAnInteger:
        servers_obj = paginator.page(1)
    except EmptyPage:
        servers_obj = paginator.page(paginator.num_pages)
    return render(request, 'assets/servers.html', {'server_list': servers_obj})


# 服务器详情
# 服务器详情页接受GET和POST请求:
# 1.GET请求,返回服务器详情信息
# 2.POST请求,接受form表单数据,写入数据库,返回服务器列表(重定向到服务器列表url)
def server_detail(request, server_id):
    server_obj = Servers.objects.get(id=server_id)
    if request.method == "POST":
        form = alpha.forms.ServersModuleForm(request.POST, instance=server_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/assets/servers')
    else:
        form = alpha.forms.ServersModuleForm(instance=server_obj)
    return render(request, 'assets/server_detail.html', {'server_info': form, 'server_id': server_id})


def server_add(request):
    form = alpha.forms.ServersModuleForm()
    if request.method == "POST":
        form = alpha.forms.ServersModuleForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/assets/servers')
        else:
            return HttpResponseRedirect('/assets/servers')
    else:
        return render(request, 'assets/server_add.html', {'server_field': form})


def server_update(request, server_id):
    if request.method == "POST":
        server_obj = Servers.objects.get(id=server_id)
        form = alpha.forms.ServersModuleForm(request.POST, instance=server_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/assets/servers')
        else:
            print(form.errors)
            return HttpResponseRedirect('/assets/servers')
    else:
        return HttpResponseRedirect('/assets/servers')


# 解决ajax post提交数据出现403
@csrf_exempt
def server_del(request):
    if request.is_ajax():
        # 获取ajax提交来的data
        hostid_obj = request.POST.get('hostid')
        hostid_list = json.loads(hostid_obj)
        for hostid in hostid_list:
            Servers.objects.filter(id=hostid).delete()
        # 定义返回数据,用于ajax回调
        return JsonResponse({'result': 'ok'})
    else:
        return HttpResponseRedirect('/assets/servers')

alpha/templates/assets/server_add.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        资产管理
        <small>资产 / 添加</small>
    </h1>
{% endblock %}
{% block content %}
<body>
    <form class="form-horizontal" action="/assets/add/" method="post">{% csrf_token %}
        {% for field in server_field %}
            <div class="form-group">
             {#field.label 获取字段名称#}
                <label class="col-sm-1 control-label">{{ field.label }}</label>
                {# 如果是'到期时间'字段,则添加一个日历选择器 #}
                <div class="col-sm-10">
{#                {% if field.label == '到期时间' %}#}
{#                    <input name="expirdate" class="serverExpirDate" type="text" placeholder="请选择日期">#}
{#                {% elif field.label == '应用' %}#}
{#                    <select multiple="multiple" name='applications' class="serverAppMultipleSelect" style="width: 130px">#}
{#                        <option value="Nginx">Nginx</option>#}
{#                        <option value="Tomcat">Tomcat</option>#}
{#                        <option value="MySQL">MySQL</option>#}
{#                        <option value="MongoDB">MongoDB</option>#}
{#                        <option value="Redis">Redis</option>#}
{#                        <option value="Confluence">Confluence</option>#}
{#                    </select>#}
{#                {% else %}#}
{#                    {{ field }}#}
{#                {% endif %}#}
                  {{ field }}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
</body>
{% endblock %}

alpha/templates/assets/server_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        资产管理
        <small>资产 / 详情</small>
    </h1>
{% endblock %}
{% block content %}
<body>
    <form id='server_detail' class="form-horizontal" action="/assets/update/{{ server_id }}/" method="post">{% csrf_token %}
        {% for field in server_info %}
            <div class="form-group">
             {#field.label 获取字段名称#}
                <label class="col-sm-1 control-label">{{ field.label }}</label>
                {# 如果是'到期时间'字段,则添加一个日历选择器 #}
                <div class="col-sm-10">
                  {{ field }}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
</body>
{% endblock %}

alpha/templates/assets/servers.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        资产管理
        <small>资产 / 列表</small>
    </h1>
{% endblock %}

{% block content %}
<div class="serverList-header"></div>
<div class="serverList-body box-body" id="servers_table">
    <div class="serverList-content text-center">
        <table class="table table-bordered">
            <thead class="serverList-thead">
                <tr style="background: #e1e4e5">
                    <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                        <input type="checkbox" name="handleAll" onclick="checkboxclick(this)">
                    </th>
                    <th class="serverList-table-th">内网IP</th>
                    <th>主机名</th>
                    <th>内存(G)</th>
                    <th>CPU(核)</th>
                    <th>数据盘(G)</th>
                    <th>系统版本</th>
                    <th>部署应用/服务</th>
                    <th>到期时间</th>
                    <th>产品线</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for server in server_list %}
                    {% if forloop.counter|divisibleby:'2' %}
                    {# 循环的次数能被2整除 #}
                        <tr style="background: #f6f6f6">
                            <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                                <input type="checkbox" name="handleHost" value="{{ server.id }}">
                            </th>
                            <td>
                                <a href="{% url 'server_detail' server.id %}">{{ server.IIP }}</a>
                            </td>
                            <td>{{ server.HostName }}</td>
                            <td>{{ server.Mem }}</td>
                            <td>{{ server.CPU }}</td>
                            <td>{{ server.DataDisk }}</td>
                            <td>{{ server.get_SystemInfo_display }}</td>
                            <td>
                                {% for app in server.Applications.all %}
                                    <a href="{% url 'app_detail' app.id %}">[{{ app.Name }}]</a>
                                {% endfor %}
                            </td>
                            <td>{{ server.ExpirationDate }}</td>
                            <td>{{ server.get_ProductItem_display }}</td>
                            <td class="{{ server.get_Status_display }}">{{ server.get_Status_display }}</td>
                            <td>
                                {% if server.Status == 0 %}
                                {# 主机状态为ON时,才可以连接 #}
                                    <a href="http://alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #91cbe8" role="button">连接</a>
                                {% else %}
                                    <a href="http:///alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs disabled" style="background-color: #91cbe8" role="button">连接</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                                <input type="checkbox" name="handleHost" value="{{ server.id }}">
                            </th>
                            <td>
                                <a href="{% url 'server_detail' server.id %}">{{ server.IIP }}</a>
                            </td>
                            <td>{{ server.HostName }}</td>
                            <td>{{ server.Mem }}</td>
                            <td>{{ server.CPU }}</td>
                            <td>{{ server.DataDisk }}</td>
                            <td>{{ server.get_SystemInfo_display }}</td>
                            {# 应用字段最长显示15个字符 #}
                            <td>
                                {% for app in server.Applications.all %}
                                    <a href="{% url 'app_detail' app.id %}">[{{ app.Name }}]</a>
                                {% endfor %}
                            </td>
                            <td>{{ server.ExpirationDate }}</td>
                            <td>{{ server.get_ProductItem_display }}</td>
                            <td class="{{ server.get_Status_display }}">{{ server.get_Status_display }}</td>
                            <td>
                                {% if server.Status == 0 %}
                                    <a href="http:///alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #91cbe8" role="button">连接</a>
                                {% else %}
                                    <a href="http:///alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs disabled" style="background-color: #91cbe8" role="button">连接</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        <form style="text-align: right" action="" method="post">{% csrf_token %}
            <a class="btn btn-primary active" style="text-align: right " href="{% url 'server_add' %}">添加</a>
            {# 删除 button 类型为button,默认是submit.submit会刷新整个页面. #}
            <button type="button" class="btn btn-danger" onclick="delhost()">删除</button>
        </form>
    </div>
    <div>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {# 左侧箭头,如果有上一页,就显示左箭头,如果当前是第一页,则不显示左箭头 #}
                {% if server_list.has_previous %}
                    <li class="enabled">
                        <a href="?page={{ server_list.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {# 中间页码 #}
                {% for page_num in server_list.paginator.page_range %}
                    {% if page_num == server_list.number %}
                        <li class="active">
                            <a href="#">{{ page_num }}<span class="sr-only">(current)</span></a>
                        </li>
                    {% else %}
                         <li class="">
                             <a href="?page={{ page_num }}">{{ page_num }}<span class="sr-only">(current)</span></a>
                         </li>
                    {% endif %}
                {% endfor %}
                {# 右侧箭头,如果有下一页,就显示右箭头,如果当前是最后一页,则不显示右箭头 #}
                {% if server_list.has_next %}
                    <li class="enabled">
                        <a href="?page={{ server_list.next_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

alpha/templates/assets/servers_bak.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        资产管理
        <small>资产 / 列表</small>
    </h1>
{% endblock %}
{% block content %}

<form action="" style="text-align:center" method="post" class="sidebar-form" >
    <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
        </button>
      </span>
    </div>
    <div class="serverList-header" style="height: 30px"></div>
    <div class="serverList-body" id="servers_table">
        <div class="serverList-content">
            <table class="table table-bordered">
                <thead class="serverList-thead">
                    <tr style="background: #e1e4e5" align="center">
                        <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                            <input type="checkbox" name="handleAll" onclick="checkboxclick(this)">
                        </th>
                        <th class="serverList-table-th">内网IP</th>
                        <th>主机名</th>
                        <th>内存(G)</th>
                        <th>CPU(核)</th>
                        <th>数据盘(G)</th>
                        <th>系统版本</th>
                        <th>部署应用/服务</th>
                        <th>到期时间</th>
                        <th>产品线</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for server in server_list %}
                        {% if forloop.counter|divisibleby:'2' %}
                        {# 循环的次数能被2整除 #}
                            <tr style="background: #f6f6f6">
                                <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                                    <input type="checkbox" name="handleHost" value="{{ server.id }}">
                                </th>
                                <td>
                                    <a href="{% url 'server_detail' server.id %}">{{ server.IIP }}</a>
                                </td>
                                <td>{{ server.HostName }}</td>
                                <td>{{ server.Mem }}</td>
                                <td>{{ server.CPU }}</td>
                                <td>{{ server.DataDisk }}</td>
                                <td>{{ server.get_SystemInfo_display }}</td>
                                <td>
                                    {% for app in server.Applications.all %}
                                        <a href="{% url 'app_detail' app.id %}">[{{ app.Name }}]</a>
                                    {% endfor %}
                                </td>
                                <td>{{ server.ExpirationDate }}</td>
                                <td>{{ server.get_ProductItem_display }}</td>
                                <td class="{{ server.get_Status_display }}">{{ server.get_Status_display }}</td>
                                <td>
                                    {% if server.Status == 0 %}
                                    {# 主机状态为ON时,才可以连接 #}
                                        <a href="http://alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #91cbe8" role="button">连接</a>
                                    {% else %}
                                        <a href="http:///alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs disabled" style="background-color: #91cbe8" role="button">连接</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                                    <input type="checkbox" name="handleHost" value="{{ server.id }}">
                                </th>
                                <td>
                                    <a href="{% url 'server_detail' server.id %}">{{ server.IIP }}</a>
                                </td>
                                <td>{{ server.HostName }}</td>
                                <td>{{ server.Mem }}</td>
                                <td>{{ server.CPU }}</td>
                                <td>{{ server.DataDisk }}</td>
                                <td>{{ server.get_SystemInfo_display }}</td>
                                {# 应用字段最长显示15个字符 #}
                                <td>
                                    {% for app in server.Applications.all %}
                                        <a href="{% url 'app_detail' app.id %}">[{{ app.Name }}]</a>
                                    {% endfor %}
                                </td>
                                <td>{{ server.ExpirationDate }}</td>
                                <td>{{ server.get_ProductItem_display }}</td>
                                <td class="{{ server.get_Status_display }}">{{ server.get_Status_display }}</td>
                                <td>
                                    {% if server.Status == 0 %}
                                        <a href="http:///alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #91cbe8" role="button">连接</a>
                                    {% else %}
                                        <a href="http:///alpha.quanshishequ.com:7110/ssh/{{ server.IIP }}" target="_blank" class="btn btn-default btn-xs disabled" style="background-color: #91cbe8" role="button">连接</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            <a class="btn btn-primary active" style="text-align: right " href="{% url 'server_add' %}">添加</a>
            {# 删除 button 类型为button,默认是submit.submit会刷新整个页面. #}
            <button type="button" class="btn btn-danger" onclick="delhost()">删除</button>
        </div>
        <div>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {# 左侧箭头,如果有上一页,就显示左箭头,如果当前是第一页,则不显示左箭头 #}
                    {% if server_list.has_previous %}
                        <li class="enabled">
                            <a href="?page={{ server_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {# 中间页码 #}
                    {% for page_num in server_list.paginator.page_range %}
                        {% if page_num == server_list.number %}
                            <li class="active">
                                <a href="#">{{ page_num }}<span class="sr-only">(current)</span></a>
                            </li>
                        {% else %}
                             <li class="">
                                 <a href="?page={{ page_num }}">{{ page_num }}<span class="sr-only">(current)</span></a>
                             </li>
                        {% endif %}
                    {% endfor %}
                    {# 右侧箭头,如果有下一页,就显示右箭头,如果当前是最后一页,则不显示右箭头 #}
                    {% if server_list.has_next %}
                        <li class="enabled">
                            <a href="?page={{ server_list.next_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</form>
{% endblock %}

alpha/templates/assets/web_term.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        资产管理
        <small>资产 / 连接</small>
    </h1>
{% endblock %}
{% block content %}
<body>
    <div id="terminal"></div>
    <script>
        var term = new Terminal({
            cols: 100,
            rows: 30,
            cursorBlink: 5,
            scrollback: 30,
            tabStopWidth: 4
        });

        <!--webssh视图返回页面点击的主机ip及server_id,在建立websocket时,
        可以传给后端.后端根据ip或者id调用paramiko处理 -->
        var host = {{ ip|safe }};
        var server_id = {{ id | safe }};
        term.open(document.getElementById('terminal'));
        term.write('root@\x1B[1;3;31m' + host + '\x1B[0m #');
        var ws = new WebSocket('ws://' + window.location.host + '/ops/websocket/' + server_id);
        ws.onerror = function() {
            console.log('connect error.');
        };

        {# 连接成功后触发的事件 #}
        ws.onopen = function() {
            console.log("connection opened!");
            ws.send(host);
            console.log('send over');
            term.on('data', function($data) {
                ws.send($data);
            });
        };

        {# 接收到服务端发来的数据后触发的事件--显示在term中 #}
        ws.onmessage = function(event) {
            term.write(event.data);
        };

        {# 连接关闭后触发的事件 #}
        ws.onclose = function() {
            console.log("connection closed");
            ws.close();
        };
    </script>
</body>
{% endblock %}