alpha/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import alpha.views
import assets
import ops


def i18n_javascript(request):
    return admin.site.i18n_javascript(request)

urlpatterns = [
    url(r'^admin/jsi18n', i18n_javascript),
    url(r'^admin/', admin.site.urls),
    url(r'^$', alpha.views.index, name='index'),
    url(r'^assets/', include('assets.urls')),
    url(r'^ops/', include('ops.urls')),
    url(r'^app/', include('applications.urls')),
    url(r'^services/', include('services.urls')),
]

applications/urls.py
from django.conf.urls import url

import applications.views


urlpatterns = [
    url(r'apps/', applications.views.apps_list, name='apps'),
    url(r'app_detail/([0-9a-zA-Z\-]{36})/$', applications.views.app_detail, name='app_detail'),
    url(r'update/([0-9a-zA-Z\-]{36})/$', applications.views.app_update, name='app_update'),
    url(r'add/', applications.views.app_add, name='app_add'),
    url(r'del/', applications.views.app_del, name='app_del'),
]

ops/urls.py
from django.conf.urls import url
from django.contrib import admin

import ops.views

urlpatterns = [
    url(r'^/', ops.views.index),
    # url(r'^ssh/([0-9a-zA-Z\-]{36})', ops.views.webssh, name='webssh'),
    # url(r'^ssh/', ops.views.webssh, name='webssh'),
    # url(r'websocket/([0-9a-zA-Z\-]{36})', ops.views.websocket, name='websocket'),
]

applications/models.py
from django.db import models

# Create your models here.

assets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

import django.utils.timezone as timezone

# Create your models here.
import uuid


product_item = (
    (0, '电商1.0'),
    (1, '电商2.0'),
    (2, '电商3.0'),
    (3, 'NEC'),
    (4, '运维支撑'),
    (5, '大数据')
)


class Servers(models.Model):

    server_status = (
        (0, 'ON'),
        (1, 'OFF'),
    )

    system_info = (
        (0, 'CentOS6.0'),
        (1, 'CentOS6.5'),
        (2, 'CentOS7.0'),
        (4, 'CentOS7.2'),
        (5, 'Windows2008'),
        (6, 'Windows2012'),
    )

    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    HostName = models.CharField(max_length=20, blank=True, null=True, verbose_name='主机名')
    EIP = models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')
    IIP = models.GenericIPAddressField(verbose_name='内网IP')
    Status = models.SmallIntegerField(choices=server_status, default=0, verbose_name='状态')
    SystemInfo = models.SmallIntegerField(choices=system_info, default=0, verbose_name='系统信息')
    Mem = models.IntegerField(default=8, verbose_name='内存')
    CPU = models.IntegerField(default=4)
    SysDisk = models.IntegerField(default=50, verbose_name='系统盘')
    DataDisk = models.IntegerField(default=500, verbose_name='数据盘')
    Applications = models.ManyToManyField('Applications', verbose_name='应用')
    ProductItem = models.SmallIntegerField(choices=product_item, default=6, verbose_name='产品线')
    ExpirationDate = models.DateField(default=timezone.now, verbose_name='到期时间')
    # verbose_name,别名,在admin后台展示时用到

    # python2.x
    def __unicode__(self):
        return self.IIP

    # python3.x
    def __str__(self):
        return self.IIP

    class Meta:
        verbose_name_plural = '服务器'
        # admin中显示的名称


class Applications(models.Model):

    application_status = (
        (0, 'ON'),
        (1, 'OFF'),
    )

    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    Name = models.CharField(max_length=20, verbose_name='应用名')
    Version = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='版本号')
    InstallDir = models.CharField(max_length=256, verbose_name='安装目录')
    Port = models.IntegerField(verbose_name='端口')
    Status = models.IntegerField(choices=application_status, default=1, verbose_name='状态')
    ProductItem = models.SmallIntegerField(choices=product_item, default=6, verbose_name='产品线')

    # python2.x
    def __unicode__(self):
        return self.Name

    # python3.x
    def __str__(self):
        return self.Name

    class Meta:
        verbose_name_plural = '应用'


class User(models.Model):

    role = (
        (0, 'user'),
        (1, 'admin')
    )

    Name = models.CharField(max_length=20, verbose_name='名字')
    Email = models.EmailField(verbose_name='邮箱')
    Head_img = models.ImageField(verbose_name='用户头像', height_field=160, width_field=160,
                                 default='static/alpha/uploads/UserHeadImg/default.jpg',
                                 upload_to='static/alpha/uploads/UserHeadImg')
    Role = models.SmallIntegerField(choices=role, default=0)

alpha/forms.py
#! _*_ coding:utf8 _*_

from django import forms
from django.forms import ModelForm
import assets.models


class ServersModuleForm(ModelForm):
    class Meta:
        # 使用模型Servers中的所有字段
        model = assets.models.Servers
        fields = '__all__'

    # 自定义ExpirationDate样式,覆盖掉之前的,新加自定义日历样式
    ExpirationDate = forms.DateField(
        widget=forms.DateTimeInput(
            attrs={'type': 'date',
                   }
        ),
        label='到期时间'
    )


class ApplicationsModuleForm(ModelForm):
    class Meta:
        model = assets.models.Applications
        fields = '__all__'

        widgets = {
            'Name': forms.Select(
                choices=(
                    ('Nginx', 'Nginx'),
                    ('Tomcat', 'Tomcat'),
                    ('MySQL', 'MySQL'),
                    ('Redis', 'Redis'),
                    ('Sentinel', 'Sentinel'),
                    ('Logstash', 'Logstash'),
                    ('Kibana', 'Kibana'),
                    ('PHP', 'PHP'),
                    ('MongoDB', 'MongoDB'),
                    ('Dubbo', 'Dubbo'),
                    ('Zabbix', 'Zabbix'),
                    ('Jenkins', 'Jenkins'),
                    ('Confluence', 'Confluence'),
                    ('Gitlab', 'Gitlab'),
                    ('FastDFS', 'FastDFS'),
                    ('Zentao', 'Zentao'),
                    ('Nexus', 'Nexus'),
                    ('Keepalived', 'Keepalived'),
                    ('Haproxy', 'Haproxy'),
                )
            )
        }

alpha/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'index.html')

applications/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from assets.models import Applications
import alpha.forms
import json


def apps_list(request):
    apps_obj = Applications.objects.all().order_by('id')
    return render(request, 'applications/apps.html', {'app_list': apps_obj})


def app_detail(request, app_id):
    app_obj = Applications.objects.get(id=app_id)
    if request.method == "POST":
        form = alpha.forms.ApplicationsModuleForm(request.POST, instance=app_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/app/apps')
    else:
        form = alpha.forms.ApplicationsModuleForm(instance=app_obj)
    return render(request, 'applications/app_detail.html', {'app_info': form, 'app_id': app_id})


def app_update(request, app_id):
    if request.method == "POST":
        app_obj = Applications.objects.get(id=app_id)
        form = alpha.forms.ApplicationsModuleForm(request.POST, instance=app_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/app/apps')
        else:
            return HttpResponseRedirect('/app/apps')
    else:
        return HttpResponseRedirect('/app/apps')


def app_add(request):
    form = alpha.forms.ApplicationsModuleForm()
    if request.method == "POST":
        form = alpha.forms.ApplicationsModuleForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/app/apps')
        else:
            return HttpResponseRedirect('/app/apps')
    else:
        return render(request, 'applications/app_add.html', {'app_field': form})


@csrf_exempt
def app_del(request):
    if request.is_ajax():
        # 获取ajax提交来的data
        appid_obj = request.POST.get('appid')
        appid_list = json.loads(appid_obj)
        for appid in appid_list:
            Applications.objects.filter(id=appid).delete()
        # 定义返回数据,用于ajax回调
        return JsonResponse({'result': 'ok'})
    else:
        return HttpResponseRedirect('/app/apps')

alpha/templates/applications/app_add.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        应用管理
        <small>应用 / 添加</small>
    </h1>
{% endblock %}
{% block content %}
<body>
    <form class="form-horizontal" action="/app/add/" method="post">{% csrf_token %}
        {% for field in app_field %}
            <div class="form-group">
             {#field.label 获取字段名称#}
                <label class="col-sm-1 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                  {{ field }}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
</body>
{% endblock %}

alpha/templates/applications/app_detail.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        资产管理
        <small>资产 / 详情</small>
    </h1>
{% endblock %}
{% block content %}
<body>
    {{ form.media }}
    <form class="form-horizontal" action="/app/update/{{ app_id }}/" method="post">{% csrf_token %}
        {% for field in app_info %}
            <div class="form-group">
                 {#field.label 获取字段名称#}
                <label class="col-sm-1 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
</body>
{% endblock %}

alpha/templates/applications/apps.html
{% extends 'base.html' %}
{% block content-title %}
    <h1>
        应用管理
        <small>应用 / 列表</small>
    </h1>
{% endblock %}
{% block content %}
<div class="serverList-header"></div>
<div class="serverList-body box-body" id="servers_table">
    <div class="serverList-content text-center">
        <table class="table table-bordered">
            <thead class="serverList-thead">
                <tr style="background: #e1e4e5">
                    <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                        <input type="checkbox" name="handleAll" onclick="checkboxclick(this)">
                    </th>
                    <th>应用名</th>
                    <th class="serverList-table-th">主机IP</th>
                    <th>安装目录</th>
                    <th>端口号</th>
                    <th>版本</th>
                    <th>状态</th>
                    <th>项目组</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for app in app_list %}
                    {% if forloop.counter|divisibleby:'2' %}
                    {# 循环的次数能被2整除 #}
                        <tr style="background: #f6f6f6">
                            <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                                <input type="checkbox" name="handleApp" value="{{ app.id }}">
                            </th>
                            <td>
                                <a href="{% url 'app_detail' app.id %}">{{ app.Name }}</a>
                            </td>
                            <td>
                                {% for iip in  app.servers_set.all %}
                                    <a href="{% url 'server_detail' iip.id %}">[{{ iip }}]</a>
                                {% endfor %}
                            </td>
                            <td>{{ app.InstallDir }}</td>
                            <td>{{ app.Port }}</td>
                            <td>{{ app.Version }}</td>
                            {# 根据状态值,现实不同颜色 #}
                            <td class="{{ app.get_Status_display }}">{{ app.get_Status_display }}</td>
                            <td>{{ app.get_ProductItem_display }}</td>
                            <td>
                                {% if app.Status == 0 %}
                                {# app状态为ON时,才可以关闭 #}
                                    <a href="http://localhost:7110/ssh/{{ app.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #9f191f" role="button">停止</a>
                                {% else %}
                                    <a href="http://localhost:7110/ssh/{{ app.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #91cbe8" role="button">启动</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <th class="text-center sorting_disabled " rowspan="1" colspan="1" aria-label style="width: 17px;">
                                <input type="checkbox" name="handleApp" value="{{ app.id }}">
                            </th>
                            <td>
                                <a href="{% url 'app_detail' app.id %}">{{ app.Name }}</a>
                            </td>
                            <td>
                                {% for iip in  app.servers_set.all %}
                                    <a href="{% url 'server_detail' iip.id %}">[{{ iip }}]</a>
                                {% endfor %}
                            </td>
                            <td>{{ app.InstallDir }}</td>
                            <td>{{ app.Port }}</td>
                            <td>{{ app.Version }}</td>
                            <td class="{{ app.get_Status_display }}">{{ app.get_Status_display }}</td>
                            <td>{{ app.get_ProductItem_display }}</td>
                            <td>
                                {% if app.Status == 0 %}
                                    <a href="http://localhost:7110/ssh/{{ app.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #9c3328" role="button">停止</a>
                                {% else %}
                                    <a href="http://localhost:7110/ssh/{{ app.IIP }}" target="_blank" class="btn btn-default btn-xs active" style="background-color: #91cbe8" role="button">启动</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        <form style="text-align: right" action="" method="post">{% csrf_token %}
            <a class="btn btn-primary active" style="text-align: right " href="{% url 'app_add' %}">添加</a>
            {# 删除 button 类型为button,默认是submit.submit会刷新整个页面. #}
            <button type="button" class="btn btn-danger" onclick="delapp()">删除</button>
        </form>
    </div>
    <div>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {# 左侧箭头,如果有上一页,就显示左箭头,如果当前是第一页,则不显示左箭头 #}
                {% if app_list.has_previous %}
                    <li class="enabled">
                        <a href="?page={{ app_list.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {# 中间页码 #}
                {% for page_num in app_list.paginator.page_range %}
                    {% if page_num == app_list.number %}
                        <li class="active">
                            <a href="#">{{ page_num }}<span class="sr-only">(current)</span></a>
                        </li>
                    {% else %}
                         <li class="">
                             <a href="?page={{ page_num }}">{{ page_num }}<span class="sr-only">(current)</span></a>
                         </li>
                    {% endif %}
                {% endfor %}
                {# 右侧箭头,如果有下一页,就显示右箭头,如果当前是最后一页,则不显示右箭头 #}
                {% if app_list.has_next %}
                    <li class="enabled">
                        <a href="?page={{ app_list.next_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div id="servercontent">

</div>
{% endblock %}